### ISSUE TITLE
Custom Registration Fields

### ISSUE THREAD

**Issue by ghost** [timersys/facebook-login#1]
Hey Damian,

I have a couple mandatory custom fields on my WP and I was wondering if you can help me out to pull out that data through your plugin. So additionally to the username and email I also have first_name, last_name, birthdate and 3 hidden fields with country (predefined), os and language.

Both os and language are have http server strings:

```
    $browser = $_SERVER['HTTP_USER_AGENT'];
    if (preg_match('/Linux/',$browser)) $os = 'Linux';
    elseif (preg_match('/Win/',$browser)) $os = 'Windows';
    elseif (preg_match('/Macintosh/',$browser)) $os = 'Mac';
    else $os = 'Unknown';

    $lang = $_SERVER['HTTP_ACCEPT_LANGUAGE'];
    if (preg_match ('/en/',$lang)) $langcode = 'en';
    elseif (preg_match ('/de/',$lang)) $langcode = 'de';
    elseif (preg_match ('/fr/',$lang)) $langcode = 'fr';
    elseif (preg_match ('/pt/',$lang)) $langcode = 'pt';
    elseif (preg_match ('/es/',$lang)) $langcode = 'es';
    elseif (preg_match ('/tr/',$lang)) $langcode = 'tr';
    elseif (preg_match ('/nl/',$lang)) $langcode = 'nl';
    elseif (preg_match ('/pl/',$lang)) $langcode = 'pl';
    elseif (preg_match ('/it/',$lang)) $langcode = 'it';
    else $langcode = 'Other';
```

I would be glad if you could help out. Donation via PayPal will be considered ;) Thx

**Comment by timersys** [comment]
Hi Candelas, please open a support request in https://wordpress.org/support/plugin/wp-facebook-login as this is for issues only.

Thanks!
