### ISSUE TITLE
Create a connect button

### ISSUE THREAD

**Issue by brianrc** [timersys/facebook-login#11]
Conversely to creating a disconnect button, what about a connect button for those who are already logged in?

I've notice you can add Facebook login to an account that has the same email as your Facebook account email, but what if a user already logged in and wants to merge the current account with a Facebook account (and the fb account happens to have a different email)?

**Comment by timersys** [comment]
I think both connect and disconnect should leave in the same place. What Im not sure about is where to place it on buddypress. Any suggestion? 
![captura de pantalla 2016-01-27 a las 6 45 19 p m](https://cloud.githubusercontent.com/assets/1206915/12629329/2a10b146-c526-11e5-81e2-457915edd08f.png)
![captura de pantalla 2016-01-27 a las 6 32 27 p m](https://cloud.githubusercontent.com/assets/1206915/12629330/2a13860a-c526-11e5-88e3-db9709545394.png)

**Comment by brianrc** [comment]
Hmm. Thanks for asking!

I would probably put it under settings -> general tab maybe below the "Account Email" input box, but I also would hope it might be something we could place ourselves somewhere like the current connect button.

**Comment by timersys** [comment]
Done - 671151464dcab9f176fc7cccd2d1b2058640e57c
