### ISSUE TITLE
Russian Names

### ISSUE THREAD

**Issue by brianrc** [timersys/facebook-login#12]
Hello, I had someone Facebook login with a Russian name "Натали Вертий" and it made their user name "-" without the quotes.

Their email was still English characters so a suggestion might be to use the first part of the email (before the @ sign) as a backup and of course run it through sanitize_title().

PS: next version going to be released soon?

**Comment by brianrc** [comment]
It just happened again. 

Russian names actually break the site because those users can't view their profiles.

**Comment by timersys** [comment]
I added a more bulletproof username generation. Let me know how it goes. https://github.com/timersys/facebook-login/commit/4d928058fc4b3461a4071c3bdf8c87cf9fb3c4ff

ps: Dunno about next version yet

**Comment by brianrc** [comment]
It's still not working. I just had someone named [ВЛАДИМИР ЧЕХ](https://www.facebook.com/app_scoped_user_id/1130502683668998/) register from Facebook and their username came out as "-" making their profile break. Their email starts with cheh68. 

I'm running Facebook Login 1.1.

**Comment by timersys** [comment]
Is time for me to open a russian facebook accoutn and try this

**Comment by timersys** [comment]
Released a new version and tested with my new Russian Facebook account :)

**Comment by brianrc** [comment]
Thank you so much. Already had one more Russian register and it appears fixed!
