### ISSUE TITLE
Lazy Load Plugin Conflict

### ISSUE THREAD

**Issue by brianrc** [timersys/facebook-login#13]
Just so ya know, there is a conflict with the [Lazy Load plugin](https://wordpress.org/plugins/lazy-load/). When active the spinner will not go away.

Also, it would be better if things were left aligned by default.

![spinner](https://cloud.githubusercontent.com/assets/573939/13242485/14204ca0-d9c3-11e5-801b-71bbfab284b9.png)

**Comment by brianrc** [comment]
Thanks for your work on this button by the way. Cool new feature!

**Comment by timersys** [comment]
Do you have a public url where I can see the lazy load problem?

**Comment by brianrc** [comment]
So I have it hidden via a css rule, but if you take the rule out you can see it on this page:
https://www.acropedia.org/order-history/

The css rule is: 

```
.woocommerce-account .css-fbl img {
    display: none!important;
}
```

**Comment by timersys** [comment]
Yep Im afraid there is nothing I can do. Your theme should configure lazy load to only work on images with certain class attribute instead of all images in site. Or enable skip_hidden option in the settings.
