### ISSUE TITLE
Instructions for FB Login App Do Not Work - Please Update

### ISSUE THREAD

**Issue by unixneo** [timersys/facebook-login#21]
Hello,

Your WP config page:

https://timersys.com/facebook-login/docs/configuration/

Instructs users to:

"https://developers.facebook.com/ and click on create new app"

That might have been correct before, but FB has made a lot of changes and there is no "new app" etc to click, so please update your configuration instructions so they are update to FB's developer page.

Thanks!

**Comment by theonlydaleking** [comment]
Still instructions issue, but different. the free plugin directs you to the config page that has the wrong shortcode. it should be: 

`[fbl_login_button hide_if_logged="false" redirect=""]`

**Comment by timersys** [comment]
Instructions are for premium version. I will make a note about it
