### ISSUE TITLE
Upgrade to Graph API v2.5 or higher

### ISSUE THREAD

**Issue by brianrc** [timersys/facebook-login#25]
Got a note from Facebook that Graph API v2.4 will reach the end of its 2-year lifetime on 09 October, 2017.

Can this plugin be upgraded to Graph API v2.5 or higher before things stop working?

https://developers.facebook.com/docs/apps/changelog/

Thanks!

**Comment by clementduncan** [comment]
I don't know much about the graph API so this could be incorrect.
The only reference to the API version is **line 160** in **public/class-facebook-login-public.php** 
which I've changed from
`https://graph.facebook.com/v2.4/'.$_POST['fb_response']['authResponse']['userID']`
to
`https://graph.facebook.com/v2.10/'.$_POST['fb_response']['authResponse']['userID']`
(2.10 is the most recent version of the graph API - [changelog](https://developers.facebook.com/docs/apps/changelog/))
I've tested 'login' which appears to work but haven't tested 'register user'.

**Comment by timersys** [comment]
included on next version
