### ISSUE TITLE
Email access not asked for

### ISSUE THREAD

**Issue by nicksss93** [timersys/facebook-login#26]
Hi,

First of all - thanks for the plugin. It's really simple and yet useful.

However, I have an issue with the Facebook permission scopes, which don't seem to work properly. When a user tries to register with Facebook, the pop-up window asks the user for access just to his public profile and not to his email, and then throws an error message that the email access is needed as well (which it really is for the purposes of the website).
From what I saw in the plugin files, it should also ask for email permission as well, so I'm not sure why it's not doing that in reality. The only profile that I have successfully connected to Facebook has been my own Facebook profile, which is also the author of the Facebook login app, so it could have taken my email from there - although I'm not sure if that's the actual reason, I'm just guessing here.

Do you have idea why this might be happening?

Thanks!

**Comment by timersys** [comment]
Hi @nicksss93 you are right about the issue. I just commited a fix for it and will release plugin update on wordpress soon.
Thanks for reporting it
