### ISSUE TITLE
Ability to change the size of the button

### ISSUE THREAD

**Issue by ghost** [timersys/facebook-login#29]
While there is a filter `fbl/login_button` for overwriting the button, I think the most common change for themes are related to the size of the button. A filter for the size would make sense.

**Comment by timersys** [comment]
Button size it's coming from facebook, you can't change it

**Comment by ghost** [comment]
There are three button sizes you can choose from:

https://developers.facebook.com/docs/facebook-login/web/login-button

**Comment by ghost** [comment]
It is true that you can choose from a predetermined set and the size is set by Facebook’s Login Button but it does not mean that the large size is best suited for all cases.

**Comment by timersys** [comment]
you are right, I will add options to change it on next version. 
Thanks!
