### ISSUE TITLE
Firefox 42.0 not working with tracking protection

### ISSUE THREAD

**Issue by Vudumen** [timersys/facebook-login#4]
In the developer console it complains about downloading the sdk js. Of course the FB object is not available and if I click on connect it gives me a ReferenceError.
Error in console: The resource at "http://connect.facebook.net/en_US/sdk.js" was blocked because tracking protection is enabled.

**Comment by timersys** [comment]
Hi Vudumen, that only happens on a private tab right?

**Comment by Vudumen** [comment]
Yes or if tracking protection is enabled in the configuration. The interesting thing that another plugin didn't have this (don't know why) but I prefer this plugin because it's really simple (user-friendly). :)

**Comment by timersys** [comment]
which another plugin?

**Comment by Vudumen** [comment]
Afair it was wordpress social login (not 100% sure sorry, I would test it but now I cannot setup a test env).

**Comment by Vudumen** [comment]
Thanks for the alert. It's fine this way :)
