### ISSUE TITLE
BuddyPress Users Can't Change Their Avatar

### ISSUE THREAD

**Issue by brianrc** [timersys/facebook-login#5]
Hello, in version 1.0.9 of Facebook Login, users can't change their avatar using the "Change Profile Photo" feature of BuddyPress. It's stuck on the Facebook avatar, which is be unexpected behavior.

Can you look into it? I think the fix involves using bp_get_user_has_avatar(), but I can't seem to get it to work correctly.

Really need this working. Thank you!!

**Comment by timersys** [comment]
Hi I was traveling sorry for the delay answering in the forums. Try the develop version please and let me know if it works for you https://github.com/timersys/facebook-login/archive/develop.zip

**Comment by brianrc** [comment]
Hi, thank you! That works, but it doesn't change the photo in the adminbar so there is now a disconnect between the photos in the admin bar and the profile photos on the page. This wouldn't be such a big deal, but the admin bar is often shown in the front end to logged in users on BuddyPres sites.

![adminbar](https://cloud.githubusercontent.com/assets/573939/11637695/e3cb9122-9cf0-11e5-9fa0-00266fb8775a.png)

**Comment by timersys** [comment]
my bad, fixed in https://github.com/timersys/facebook-login/commit/b7bf9a31b6c8cbb7119920b90c4df4548d329d1f
