### ISSUE TITLE
Two spinners

### ISSUE THREAD

**Issue by brianrc** [timersys/facebook-login#6]
Don't know why, but there are now two spinny things when logining in. 
![spinnythings](https://cloud.githubusercontent.com/assets/573939/11638798/ca6e548e-9cf6-11e5-9d77-ff7695bb7413.png)

**Comment by timersys** [comment]
how are you adding that button? Or how I can reproduce the error?

**Comment by brianrc** [comment]
I'm adding it like this:

```
/* add Facebook login button to registration screen */
function bws_render_facebook_login_on_register_form() {
  do_action('facebook_login_button');
}
add_action( 'bp_before_account_details_fields', 'bws_render_facebook_login_on_register_form' );
```

**Comment by timersys** [comment]
sure that spinner is not added by your there or smt ? I don't remember using that :S

**Comment by brianrc** [comment]
I think I found the culprit. Some css in the BuddyBoss theme. Thank you.

```
#buddypress a.loading:after,
#buddypress button.loading:after,
#buddypress ul li.loading a:after {
    font-family: 'FontAwesome';
    font-weight: normal;
    font-style: normal;
    text-rendering: auto;
    text-decoration: inherit;
    speak: none;
    display: inline-block;
    line-height: 1;
    content: "\f110";
    font-size: 14px;
    -webkit-font-smoothing: antialiased;
    color: #999;
    text-decoration: none;
    margin-left: 8px;
    padding: 0;

    -webkit-animation: spin 2s infinite linear;
    -moz-animation: spin 2s infinite linear;
    -o-animation: spin 2s infinite linear;
    animation: spin 2s infinite linear;
}
```

**Comment by timersys** [comment]
I think I changed the loading class to avoid this issues, maybe I did on pro version only . I will check. Thanks!

**Comment by timersys** [comment]
Renamed loading class to avoid issues https://github.com/timersys/facebook-login/commit/70c6031d6ad433b652a606a5b47529d1b39bf98a
