### ISSUE TITLE
Group avatar doesn't automatically load when set with "Facebook Avatars?" option true

### ISSUE THREAD

**Issue by brianrc** [timersys/facebook-login#7]
When "Facebook Avatars?" option is checked, setting a group avatar doesn't load the image automatically while it does when the "Facebook Avatars?" option isn't checked or the Facebook Login plugin is disabled. 

This is using BuddyPress 2.4.2 and it's broken in both Facebook Login 1.0.10 and the current development branch.

**Comment by timersys** [comment]
Fixed on https://github.com/timersys/facebook-login/commit/332396cdfa84f771c4ca3546579ec7cafda8457a

**Comment by brianrc** [comment]
Confirmed fixed!
