### ISSUE TITLE
Default Avatar settings bugged

### ISSUE THREAD

**Issue by brianrc** [timersys/facebook-login#8]
When you log in through Facebook (and you're a site admin) the WP Admin -> Setting -> Discussion -> Default Avatar settings are bugged. All the options become your Facebook avatar. See screenshot.

![default-avatar](https://cloud.githubusercontent.com/assets/573939/12069093/a938541e-afec-11e5-88ac-3477bfa5e12a.png)

**Comment by timersys** [comment]
Can't reproduce, probably fixed in https://github.com/timersys/facebook-login/commit/332396cdfa84f771c4ca3546579ec7cafda8457a

**Comment by brianrc** [comment]
Confirmed fixed. Thank you!
